<?php

namespace GCSV\RaportBundle\Entity;

/**
 * RaportTechnicznyExtraFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaportTechnicznyExtraFieldRepository extends \Doctrine\ORM\EntityRepository
{
}
