<?php

namespace GCSV\RaportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaportZuzyciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaportZuzyciaRepository extends EntityRepository
{
}
