<?php

namespace GCSV\RaportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaportZuzyciaProduktRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaportZuzyciaProduktRepository extends EntityRepository
{
}
