<?php

namespace GCSV\MagazynBundle\Entity;

use Doctrine\ORM\EntityRepository;
use GCSV\UserBundle\Entity\Uzytkownik;

/**
 * Magazyn
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StanMagazynuMAXRepository extends EntityRepository
{
    public function wyswietlMojStanMagazynowyMAXQuery(Uzytkownik $user)
    {
        if(!$user->getMagazyn())
        {
            return false;
        }

        $query = $this->createQueryBuilder('sm')
            ->select('sm,mag,prod')
            ->leftJoin('sm.magazyn','mag')
            ->leftJoin('sm.produkt','prod')
            ->where('mag.symbol = :symbol')
            ->setParameter('symbol',$user->getMagazyn()->getSymbol())
            ->orderBy('sm.wartosc','ASC')
            ->getQuery()->getResult();

        return $query;
    }
}