<?php

namespace GCSV\MagazynBundle\Entity;

use Doctrine\ORM\EntityRepository;
use GCSV\UserBundle\Entity\Uzytkownik;

/**
 * Magazyn
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StanMagazynuWirtualnyRepository extends EntityRepository
{
    public function wyswietlMojStanMagazynowyWirtualnyQuery(Uzytkownik $user)
    {
        $query = $this->createQueryBuilder('sm')
            ->select('sm,u,p')
            ->leftJoin('sm.uzytkownik','u')
            ->leftJoin('sm.produkt','p')
            ->where('sm.uzytkownik = :user')
            ->setParameter('user',$user->getId())
            ->orderBy('sm.wartosc','ASC')
            ->getQuery()->getResult();

        return $query;
    }
}