<?php

namespace DFP\EtapIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliaRepository extends EntityRepository
{
    public function znajdzWszystkieFilie($klient)
    {

    }

    public function findOneByZip($zip)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT f FROM DFPEtapIBundle:Filia f WHERE f.kodPocztowy = :zip")
            ->setParameter("zip",$zip)
            ->getOneOrNullResult();
    }
}
