<?php

namespace DFP\EtapIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KlientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KlientRepository extends EntityRepository
{
    public function findOneByNIP($numer)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT
                  k
                FROM
                  DFPEtapIBundle:Klient k
                WHERE
                  k.nip = :nip'
            )
            ->setParameter('nip',$numer)
            ->getOneOrNullResult();
    }

    public function getListaKlientowQuery()
    {
        $query = $this->getEntityManager()->getRepository('DFPEtapIBundle:Klient')->createQueryBuilder('k')
            ->select('k,f,fu,u,gk')
            ->leftJoin('k.filie','f')
            ->leftJoin('f.filieUzytkownicy','fu')
            ->leftJoin('fu.uzytkownik','u')
            ->leftJoin('k.grupyKlientow','gk')
            ->getQuery();

        return $query;
    }
}
