<?php

namespace DFP\EtapIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KolorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KolorRepository extends EntityRepository
{
    public function getListaKolorow($term)
    {
        $query  = $this->getEntityManager()->getRepository('DFPEtapIBundle:Kolor')->createQueryBuilder('k')
            ->select('k')
            ->where('k.nazwa LIKE :term')
            ->setParameter('term',"$term%")
            ->setMaxResults(10)
            ->getQuery();

        return $result = $query->getResult();
    }

    public function getListaProduktowSearchQuery($kryteria = null)
    {
        $query = $this->getEntityManager()->getRepository('DFPEtapIBundle:Produkt')->createQueryBuilder('p')
            ->select('p')
            ->orderBy('p.nazwaHandlowa','ASC');

        if($kryteria)
        {
            $pole = $kryteria['filterField'];
            $wartosc = $kryteria['filterValue'];
            $query->where("$pole LIKE '%$wartosc%'");
        }

        $query->getQuery();

        return $query;
    }
}
