<?php

namespace DFP\EtapIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaHandlowaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaHandlowaRepository extends EntityRepository
{
    public function getListaOczekujacychNaDoborSystemuMalarskiegoQuery()
    {
        $query = $this->getEntityManager()->getRepository('DFPEtapIBundle:OfertaHandlowa')->createQueryBuilder('oh')
            ->select('oh','f','uz','k','pd')
            ->innerJoin('oh.filia','f')
            ->leftJoin('f.klient','k')
            ->leftJoin('f.profileDzialalnosci','pd')
            ->innerJoin('oh.zamawiajacy','uz')
            ->where('oh.status IN (0,1)')
            ->getQuery();

        return $query;
    }

    public function getListaOczekujacychNaOpracowanieOfertyHandlowejQuery()
    {
        $query = $this->getEntityManager()->getRepository('DFPEtapIBundle:OfertaHandlowa')->createQueryBuilder('oh')
            ->select('oh','f','uz','k','pd')
            ->innerJoin('oh.filia','f')
            ->leftJoin('f.klient','k')
            ->leftJoin('f.profileDzialalnosci','pd')
            ->innerJoin('oh.zamawiajacy','uz')
            ->where('oh.status IN (2,3)')
            ->getQuery();

        return $query;
    }

    public function findWTrakciePrzygotowania($filia)
    {
        $query = $this->getEntityManager()->getRepository('DFPEtapIBundle:OfertaHandlowa')->createQueryBuilder('oh')
            ->select('oh')
            ->where('oh.status != 4')
            ->andWhere('oh.filia = :id')
            ->setParameter('id',$filia)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
