<?php

namespace DFP\EtapIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProcesPrzygotowaniaPowierzchniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesPrzygotowaniaPowierzchniRepository extends EntityRepository
{
}
