<?php

namespace DFP\EtapIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduktyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduktRepository extends EntityRepository
{
    public function getListaProduktowSearchQuery($kryteria = null)
    {
        $query = $this->getEntityManager()->getRepository('DFPEtapIBundle:Produkt')->createQueryBuilder('p')
            ->select('p')
            ->orderBy('p.nazwaHandlowa','ASC');

        if($kryteria)
        {
            $pole = $kryteria['filterField'];
            $wartosc = $kryteria['filterValue'];
            $query->where("$pole LIKE '%$wartosc%'");
        }

        $query->getQuery();

        return $query;
    }
}
