<?php

namespace DFP\EtapIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SystemMalarskiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemMalarskiRepository extends EntityRepository
{
    public function getListaSystemowMalarskichSearchQuery($kryteria = null)
    {
        $query = $this->getEntityManager()->getRepository('DFPEtapIBundle:SystemMalarski')->createQueryBuilder('sm')
            ->select('sm');

        if($kryteria)
        {
            $pole = $kryteria['filterField'];
            $wartosc = $kryteria['filterValue'];
            $query->where("$pole LIKE '%$wartosc%'");
        }

        $query->getQuery();

        return $query;
    }
}
