<?php

namespace DFP\EtapIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UzytkownikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UzytkownikRepository extends EntityRepository
{
    public function getAllUsersQuery()
    {
        $query = $this->createQueryBuilder('u')
            ->select('u,pu')
            ->leftJoin('u.profilUzytkownika','pu')
            ->orderBy('u.imie')
            ->getQuery();

        return $query;
    }

    public function getAllPrzypisani()
    {
        $query = $this->createQueryBuilder('u')
            ->select('u,fu')
            ->leftJoin('u.filieUzytkownicy','fu')
            ->leftJoin('fu.filia','f')
            ->orderBy('u.imie','ASC')
            ->getQuery();

        return $query->getResult();
    }
}
