services:
    gcsv.technicalbundle.calendar_listener:
        class: 'GCSV\TechnicalBundle\EventListener\KalendarzEventListener'
        arguments: ['@doctrine.orm.entity_manager','@form.csrf_provider']
        tags:
            - { name: 'kernel.event_listener', event: 'calendar.load_events', method: 'loadEvents' }

    gcsv.technicalbundle.zdarzenie_techniczne.subscriber:
        class:  GCSV\TechnicalBundle\EventListener\ZdarzenieTechniczneSubscriber
        arguments:  [@service_container]
        tags:
            - { name: doctrine.event_subscriber }

    gcsv.type.zdarzenie_techniczne_hidden:
        class:  GCSV\TechnicalBundle\Form\Type\ZdarzenieTechniczneHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type,  alias:  zdarzenie_techniczne_hidden }

    gcsv.technicalbundle.upload_listener:
        class:  GCSV\TechnicalBundle\EventListener\UploadListener
        tags:
            - { name: kernel.event_listener, event: 'oneup_uploader.post_upload', method: 'onUpload' }

    gcsv.technicalbundle.upload_namer:
        class:  GCSV\TechnicalBundle\ZalacznikNamer

    gcsv.form.type.datetime_hidden:
        class:  GCSV\TechnicalBundle\Form\Type\DateTimeHiddenType
        tags:
            - { name: form.type, alias: datetime_hidden }

    gcsv.technicalbundle.form.type.autocomplete:
        class: GCSV\TechnicalBundle\Form\Type\FirmaOddzialAutocompleteType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type, alias: gcsv_firma_oddzial_autocomplete }